version: "3.8"
services:
  flask:
    build: ./flask-vue-crud/server
    container_name: flask
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
    networks:
      - appnet
    ports:
      - "5000:5000"

  vue:
    build: ./flask-vue-crud/client
    container_name: vue
    expose:
      - 80
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - flask
      - vue
    networks:
      - appnet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
